import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");
const { height } = Dimensions.get("window");

const styles = StyleSheet.create({
  container: {
    flex: 1,
    display: "flex",
    backgroundColor: "#96DFFF",
    alignItems: "center",
  },
  currTemp: {
    position: "absolute",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    top: 225,
    width: 214,
    height: 214,
    backgroundColor: "#43ACD9",
    borderRadius: 107,
  },
  currTempText: {
    color: "white",
    fontSize: 65,
    fontWeight: "bold",
    paddingLeft: 35,
  },
  currTempTextTitle: {
    color: "white",
    fontSize: 20,
    textAlign: "center",
  },
  maxTemp: {
    position: "absolute",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    top: 145,
    left: 235,
    width: 99,
    height: 99,
    backgroundColor: "#43ACD9",
    borderRadius: 50,
  },
  maxTempText: {
    color: "white",
    fontSize: 25,
    fontWeight: "bold",
    paddingLeft: 15,
  },
  maxTempTextTitle: {
    color: "white",
    fontSize: 10,
    textAlign: "center",
  },
  minTemp: {
    position: "absolute",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    top: 80,
    left: 300,
    width: 66,
    height: 66,
    backgroundColor: "#43ACD9",
    borderRadius: 50,
  },
  minTempText: {
    color: "white",
    fontSize: 20,
    fontWeight: "bold",
    paddingLeft: 5,
  },
  minTempTextTitle: {
    color: "white",
    fontSize: 10,
    textAlign: "center",
  },
  rect: {
    display: "flex",

    backgroundColor: "#43ACD9",
    width: width * 0.9,
    height: height * 0.3,
    borderRadius: 25,
    position: "absolute",
    top: height * 0.67,
  },
  rectCityText: {
    color: "white",
    fontSize: 35,
    fontWeight: "bold",
    padding: 20,
    paddingBottom: 10,
  },
  rectDescText: {
    color: "white",
    fontSize: 20,
    fontWeight: "bold",
    paddingLeft: 50,
    paddingBottom: 10,
  },
  rectPrecProbText: {
    color: "white",
    fontSize: 20,
    fontWeight: "bold",
    paddingLeft: 20,
    paddingBottom: 10,
  },
  button: {
    display: "flex",
    backgroundColor: "#96DFFF",
    height: height * 0.05,
    width: width * 0.2,
    marginTop: 10,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
  },
  dayContainer: {
    display: "flex",
    alignItems: "center",
  },
  modalTemp: {
    color: "white",
    fontSize: 50,
    fontWeight: "bold",
  },
  modalWind: {
    paddingLeft: 3,
    color: "white",
    fontSize: 25,
    fontWeight: "bold",
    alignSelf: "flex-start",
  },
  modalCond: {
    paddingTop: 15,
    paddingLeft: 25,
    paddingRight: 3,
    color: "white",
    fontSize: 25,
    fontWeight: "bold",
    alignSelf: "flex-end",
  },
  modalCondVal: {
    paddingLeft: 25,
    paddingBottom: 15,
    paddingRight: 3,
    color: "white",
    fontSize: 20,
    fontWeight: "bold",
    alignSelf: "flex-end",
  },
  modalHum: {
    paddingLeft: 3,
    paddingRight: 25,
    paddingBottom: 15,
    color: "white",
    fontSize: 25,
    fontWeight: "bold",
    alignSelf: "flex-start",
  },
  buttonContainer: {
    alignSelf: "flex-start",
    width: width,
    display: "flex",
    flex: 1,
    alignContent: "flex-end",
  },

  modalNavButtons: {
    backgroundColor: "#2196f3",
    color: "white",
    height: 40,
    width: 100,
  },

  modalBack: {
    color: "white",
    fontSize: 50,
    paddingLeft: 15,
  },
  buttonContainer1: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: width,
    paddingHorizontal: 10,
    marginTop: 10,
  },
  modalNavButtons1: {
    width: 100,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#43ACD9",
  },
});
export default styles;
